import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Color.fromARGB(255, 255, 255, 255),
      ),
      home: Scaffold(
        body: ListView(children: [
          Rectangle4197(),
        ]),
      ),
    );
  }
}

class Rectangle4197 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(height: 20),
        SizedBox(height: 20),
        Container(
          width: 350,
          height: 200,
          decoration: ShapeDecoration(
            color: Color.fromARGB(15, 132, 170, 219),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          child: Row(
            children: [
              Expanded(
                child: SizedBox(),
              ),
              Container(
                width: 100, // Largura da imagem
                height: 90, // Altura da imagem
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage('assets/images/card11.png'),
                    fit: BoxFit.fill,
                  ),
                ),
              ),
              Container(
                alignment: Alignment.centerRight,
                width: 100,
                height: 24,
                decoration: ShapeDecoration(
                  color: Color(0xB200255E),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 0,
                child: Align(
                  child: SizedBox(
                    width: 103,
                    height: 25,
                    child: Text(
                      'Total R\$ 10,00',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                        height: 1.5599023104,
                        letterSpacing: -0.48,
                        fontStyle: FontStyle.italic,
                        color: Color(0xffffffff),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        )
      ],
    );
  }
}
